### PR TITLE
Addressing #10.

### LINKED ISSUE #10: Improve StorageDoubleMap Key Checking - Trust Pallet
Right now we're using try_get to check if a key pair exists in a StorageDoubleMap. There's already a function for this that I somehow missed.

### PR DESCRIPTION
**Pull request by Romulus10**
This closes #10 - just take a glance and make sure it still makes sense.

### CODE REVIEW

**Comment by isaacadams** [comment]
`request_trust` and `issue_trust` should be opposite contains_key

**Comment by isaacadams** [comment]
> `request_trust` and `issue_trust` should be opposite contains_key

`revoke_trust` as well

**Comment by Romulus10** [comment]
> > `request_trust` and `issue_trust` should be opposite contains_key
> 
> `revoke_trust` as well

Good catch - somehow this passed tests.

**Comment by isaacadams** [comment]
> > > `request_trust` and `issue_trust` should be opposite contains_key
> > 
> > 
> > `revoke_trust` as well
> 
> Good catch - somehow this passed tests.

do tests need to be added/changed?

**Comment by Romulus10** [comment]
> > > > `request_trust` and `issue_trust` should be opposite contains_key
> > > 
> > > 
> > > `revoke_trust` as well
> > 
> > 
> > Good catch - somehow this passed tests.
> 
> do tests need to be added/changed?

I was just looking at that. I _think_ they're okay?

**Review by isaacadams — APPROVED** [review]

**Pull request merged**
