### PR TITLE
update dependencies to latest polkadot

### PR DESCRIPTION
**Pull request by insipx**

### CODE REVIEW

**Comment by insipx** [comment]
hold merge probably doesn't have required chain specs

**Comment by Romulus10** [comment]
@insipx Whenever you're ready to merge this, I am too.

**Comment by insipx** [comment]
zombienet config is basically done, i'm just upgrading this to the latest 9.37 before merging

**Comment by Romulus10** [comment]
What is this waiting on? It looks like we need some things done in here for our review, if we just need to merge and fix conflicts I can do that.

**Comment by insipx** [comment]
I updated this to fix the benchmarks and tests.

- changed to be based on cumulus rather than standalone chain. this will allow a [zombienet](https://github.com/paritytech/zombienet) configuration and testing as a parachain with Polkadot.
- all extrinsics include a new `call_index` attribute
- a new benchmarking script taken from the smart folks at Astar is included in `scripts/run_benchmarks.sh`.
- all weight data is stored along with the pallets (i.e the trait declaration and implementation on `SubstrateWeights` type). This allows extracting all frame pallets into a separate repository if we choose to.
- runtime updated to `0.9.37`

**Comment by Romulus10** [comment]
> @Romulus10 I updated this to fix the benchmarks and tests.
> 
>     * changed to be based on cumulus rather than standalone chain. this will allow a [zombienet](https://github.com/paritytech/zombienet) configuration and testing as a parachain with Polkadot.
> 
>     * all extrinsics include a new `call_index` attribute
> 
>     * a new benchmarking script taken from the smart folks at Astar is included in `scripts/run_benchmarks.sh`.
> 
>     * all weight data is stored along with the pallets (i.e the trait declaration and implementation on `SubstrateWeights` type). This allows extracting all frame pallets into a separate repository if we choose to.
> 
>     * runtime updated to `0.9.37`

Absolutely spectacular. Thanks again. This should clean everything up a _ton_.

**Comment by insipx** [comment]
FWIW the latest substrate version is ~0.9.41, but this PR will make updating to that version much easier

**Review by Romulus10 — APPROVED** [review]

**Comment by Romulus10** [comment]
Good to go - let me know if you want to do something else before we merge, otherwise I'll merge it on in tonight. @insipx

**Comment by insipx** [comment]
this should be good to go!

**Comment by Romulus10** [comment]
> this should be good to go!

Beautiful. Merging on in. Thanks again!

**Pull request merged**
